### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Chomikmarkus** [456478/proxy-captcha#1]
Is your telegram actual? Trying to reach you

**Comment by 456478** [comment]
ofc it's real. added back email to my profile as well: ee dot narkootikumid at github, backwards. saw some people couldn't actually write a proper email and it got sent straight to spam hell lol. can't believe how people who are phishing can't even get through the spam filter with regular emails

**Comment by Chomikmarkus** [comment]
Sent you mail!
